### ISSUE TITLE
recurrence

### ISSUE THREAD

**Issue by clive-g-brown** [jinyeom/neat#2]
any chance of recurrent connections ?

**Comment by jinyeom** [comment]
Yup! Currently, I purposely made it so that the networks CAN evolve into recurrent networks, but actually I'm thinking about getting rid of recurrency, so that I can easily add backprop (along with options like Baldwin effect or Lamarckian evolution).

**Comment by clive-g-brown** [comment]
plz don’t get rid of recurrence, make it a user option.

**Comment by jinyeom** [comment]
Alrighty
